set hive.exec.dynamic.partition=true;
set hive.exec.dynamic.partition.mode=nonstrict;
--计算连续N日留存用户数RetentionByNumDay
insert into noapp_retention_count_day
select a.t_date,a.user_type,count(1) as user_count
 from(select '${startDate}' as t_date,user_type,sn as user_id,count(distinct concat(y,m,d)) as days_num from events_type_log
 where concat(y,'-',m,'-',d)>='${startDate}' and concat(y,'-',m,'-',d)<='${endDate}'
group by 2,3  having (datediff('${endDate}','${startDate}') = days_num-1)
) a group by 1,2