<link rel="stylesheet" type="text/css" href="/resources/plugin/easyui/css/common.css?version=${version}">
<link rel="stylesheet" type="text/css" href="/resources/plugin/easyui/css/prettify.css">
<link rel="stylesheet" type="text/css" href="/resources/plugin/easyui/css/icon.css">
<link rel="stylesheet" type="text/css" href="/resources/plugin/easyui/css/skin01.css" id="cssfile">
<link rel="stylesheet" type="text/css" href="/resources/css/style.css">
