 <script type="text/javascript" src="/resources/plugin/easyui/js/jquery.min.js"></script>
 <script type="text/javascript" src="/resources/plugin/easyui/js/jquery.json-2.4.min.js"></script>
 <script type="text/javascript" src="/resources/plugin/easyui/js/prettify.js"></script>
<script type="text/javascript" src="/resources/plugin/easyui/js/jquery.easyui.min.js"></script>
<script type="text/javascript" src="/resources/plugin/easyui/js/easyui-lang-zh_CN.js"></script>
<script type="text/javascript" src="/resources/plugin/easyui/js/jquery.cookie.js"></script>
<script type="text/javascript" src="/resources/plugin/easyui/js/changeSkin.js"></script>
<script type="text/javascript" src="/resources/plugin/uploadify/jquery.uploadify.min.js"></script>
<script type="text/javascript" src="/resources/plugin/easyui/js/date/WdatePicker.js"></script>
<script type="text/javascript" >
var titleInfo="提示信息";
</script>